-------------------------------------------------------------------------------
Test set: at.fhtw.swen3.OpenApiGeneratorApplicationTests
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.317 s <<< FAILURE! - in at.fhtw.swen3.OpenApiGeneratorApplicationTests
contextLoads  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: at.fhtw.swen3.persistence.entities.WarehouseNextHopsEntity.warehouse_next_hop in at.fhtw.swen3.persistence.entities.WarehouseEntity.nextHops
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: at.fhtw.swen3.persistence.entities.WarehouseNextHopsEntity.warehouse_next_hop in at.fhtw.swen3.persistence.entities.WarehouseEntity.nextHops

